package com.genea.enums;

public enum ProductCategory {
    ELECTRONICS, CLOTHING, HOME, KITCHEN,  BOOKS, FURNITURE, FITNESS, TOYS, FEMALE_SHOES
    ,MALE_SHOES, UNISEX_SHOES, BAG, JEWELRY, WATCHES, BEAUTY, HEALTH, SPORTS, AUTOMOTIVE, GROCERY, PET, TOOLS
}
